apiVersion: v1
kind: Service
metadata:
  name: server-headless
spec:
  clusterIP: None
  selector:
    app: server
  ports:
    - port: 80
      targetPort: {{ .Values.server.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - port: 80
      targetPort: {{ .Values.server.port }}
